apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opensky-producer-monitor
  namespace: opensky
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: opensky-producer
  endpoints:
  - port: http
    interval: 15s
    path: /metrics